// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once


#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CnaRoom::Effects::detail::AutoExposureGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "auto_exposure";
inline constexpr std::string_view kManifestSha256 = "f5e2d984aa1642bd19e0ef948b6eb613797ecf0e70eba191ed472692fdf07eeb";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";
inline constexpr std::string_view kWgslTranslator = "naga-cli";
inline constexpr std::string_view kWgslTranslatorVersion = "28.0.0";
inline constexpr std::string_view kWgslTranslatorSha256 = "6721540d62bd3f618ca4c19ab1b70033a5a286a69e34e1eeca38079bdf392481";
inline constexpr std::string_view kWgslSourceTransform = "cna-webgpu-glsl/1";

inline constexpr std::string_view kReductionEsComputeSource =
    R"CNA_SHADER(#version 310 es
precision highp float;

layout(local_size_x = 8, local_size_y = 8) in;
uniform sampler2D uScene;
layout(std430, binding = 1) writeonly buffer Partials
{
    float partials[];
};
shared float sharedSums[64];

void main()
{
    vec2 grid = vec2(gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);
    vec2 uv = (vec2(gl_GlobalInvocationID.xy) + 0.5) / grid;
    vec3 colour = texture(uScene, uv).rgb;
    float luminance = dot(colour, vec3(0.2126, 0.7152, 0.0722));
    float value = log(max(luminance, 1e-4));

    uint local = gl_LocalInvocationIndex;
    sharedSums[local] = value;
    memoryBarrierShared();
    barrier();
    for (uint stride = 32u; stride > 0u; stride >>= 1u)
    {
        if (local < stride)
            sharedSums[local] += sharedSums[local + stride];
        memoryBarrierShared();
        barrier();
    }
    if (local == 0u)
    {
        uint group = gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x;
        partials[group] = sharedSums[0];
    }
}
)CNA_SHADER";

inline constexpr std::string_view kReductionDesktopComputeSource =
    R"CNA_SHADER(#version 430 core

layout(local_size_x = 8, local_size_y = 8) in;
uniform sampler2D uScene;
layout(std430, binding = 1) writeonly buffer Partials
{
    float partials[];
};
shared float sharedSums[64];

void main()
{
    vec2 grid = vec2(gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);
    vec2 uv = (vec2(gl_GlobalInvocationID.xy) + 0.5) / grid;
    vec3 colour = texture(uScene, uv).rgb;
    float luminance = dot(colour, vec3(0.2126, 0.7152, 0.0722));
    float value = log(max(luminance, 1e-4));

    uint local = gl_LocalInvocationIndex;
    sharedSums[local] = value;
    memoryBarrierShared();
    barrier();
    for (uint stride = 32u; stride > 0u; stride >>= 1u)
    {
        if (local < stride)
            sharedSums[local] += sharedSums[local + stride];
        memoryBarrierShared();
        barrier();
    }
    if (local == 0u)
    {
        uint group = gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x;
        partials[group] = sharedSums[0];
    }
}
)CNA_SHADER";

inline constexpr std::uint32_t kReductionVulkanComputeSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000082u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0009000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000du, 0x00000016u, 0x0000003cu,
    0x0000006au, 0x00060010u, 0x00000004u, 0x00000011u, 0x00000008u, 0x00000008u, 0x00000001u, 0x00040047u,
    0x0000000du, 0x0000000bu, 0x00000018u, 0x00040047u, 0x00000016u, 0x0000000bu, 0x0000001cu, 0x00040047u,
    0x00000025u, 0x00000021u, 0x00000000u, 0x00040047u, 0x00000025u, 0x00000022u, 0x00000000u, 0x00040047u,
    0x0000003cu, 0x0000000bu, 0x0000001du, 0x00040047u, 0x0000006au, 0x0000000bu, 0x0000001au, 0x00040047u,
    0x00000073u, 0x00000006u, 0x00000004u, 0x00030047u, 0x00000074u, 0x00000003u, 0x00040048u, 0x00000074u,
    0x00000000u, 0x00000019u, 0x00050048u, 0x00000074u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u,
    0x00000076u, 0x00000019u, 0x00040047u, 0x00000076u, 0x00000021u, 0x00000001u, 0x00040047u, 0x00000076u,
    0x00000022u, 0x00000000u, 0x00040047u, 0x0000007eu, 0x0000000bu, 0x00000019u, 0x00020013u, 0x00000002u,
    0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u,
    0x00000006u, 0x00000002u, 0x00040015u, 0x0000000au, 0x00000020u, 0x00000000u, 0x00040017u, 0x0000000bu,
    0x0000000au, 0x00000003u, 0x00040020u, 0x0000000cu, 0x00000001u, 0x0000000bu, 0x0004003bu, 0x0000000cu,
    0x0000000du, 0x00000001u, 0x00040017u, 0x0000000eu, 0x0000000au, 0x00000002u, 0x0004002bu, 0x0000000au,
    0x00000011u, 0x00000008u, 0x0005002cu, 0x0000000eu, 0x00000012u, 0x00000011u, 0x00000011u, 0x0004003bu,
    0x0000000cu, 0x00000016u, 0x00000001u, 0x0004002bu, 0x00000006u, 0x0000001au, 0x3f000000u, 0x00040017u,
    0x0000001fu, 0x00000006u, 0x00000003u, 0x00090019u, 0x00000022u, 0x00000006u, 0x00000001u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000001u, 0x00000000u, 0x0003001bu, 0x00000023u, 0x00000022u, 0x00040020u,
    0x00000024u, 0x00000000u, 0x00000023u, 0x0004003bu, 0x00000024u, 0x00000025u, 0x00000000u, 0x00040017u,
    0x00000028u, 0x00000006u, 0x00000004u, 0x0004002bu, 0x00000006u, 0x00000029u, 0x00000000u, 0x0004002bu,
    0x00000006u, 0x0000002fu, 0x3e59b3d0u, 0x0004002bu, 0x00000006u, 0x00000030u, 0x3f371759u, 0x0004002bu,
    0x00000006u, 0x00000031u, 0x3d93dd98u, 0x0006002cu, 0x0000001fu, 0x00000032u, 0x0000002fu, 0x00000030u,
    0x00000031u, 0x0004002bu, 0x00000006u, 0x00000036u, 0x38d1b717u, 0x00040020u, 0x0000003bu, 0x00000001u,
    0x0000000au, 0x0004003bu, 0x0000003bu, 0x0000003cu, 0x00000001u, 0x0004002bu, 0x0000000au, 0x0000003eu,
    0x00000040u, 0x0004001cu, 0x0000003fu, 0x00000006u, 0x0000003eu, 0x00040020u, 0x00000040u, 0x00000004u,
    0x0000003fu, 0x0004003bu, 0x00000040u, 0x00000041u, 0x00000004u, 0x00040020u, 0x00000044u, 0x00000004u,
    0x00000006u, 0x0004002bu, 0x0000000au, 0x00000046u, 0x00000001u, 0x0004002bu, 0x0000000au, 0x00000047u,
    0x00000108u, 0x0004002bu, 0x0000000au, 0x00000048u, 0x00000002u, 0x0004002bu, 0x0000000au, 0x0000004au,
    0x00000020u, 0x0004002bu, 0x0000000au, 0x00000051u, 0x00000000u, 0x00020014u, 0x00000052u, 0x0004003bu,
    0x0000000cu, 0x0000006au, 0x00000001u, 0x0003001du, 0x00000073u, 0x00000006u, 0x0003001eu, 0x00000074u,
    0x00000073u, 0x00040020u, 0x00000075u, 0x00000002u, 0x00000074u, 0x0004003bu, 0x00000075u, 0x00000076u,
    0x00000002u, 0x00040015u, 0x00000077u, 0x00000020u, 0x00000001u, 0x0004002bu, 0x00000077u, 0x00000078u,
    0x00000000u, 0x00040020u, 0x0000007cu, 0x00000002u, 0x00000006u, 0x0006002cu, 0x0000000bu, 0x0000007eu,
    0x00000011u, 0x00000011u, 0x00000046u, 0x0005002cu, 0x00000007u, 0x00000081u, 0x0000001au, 0x0000001au,
    0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003du,
    0x0000000bu, 0x0000000fu, 0x0000000du, 0x0007004fu, 0x0000000eu, 0x00000010u, 0x0000000fu, 0x0000000fu,
    0x00000000u, 0x00000001u, 0x00050084u, 0x0000000eu, 0x00000013u, 0x00000010u, 0x00000012u, 0x00040070u,
    0x00000007u, 0x00000014u, 0x00000013u, 0x0004003du, 0x0000000bu, 0x00000017u, 0x00000016u, 0x0007004fu,
    0x0000000eu, 0x00000018u, 0x00000017u, 0x00000017u, 0x00000000u, 0x00000001u, 0x00040070u, 0x00000007u,
    0x00000019u, 0x00000018u, 0x00050081u, 0x00000007u, 0x0000001cu, 0x00000019u, 0x00000081u, 0x00050088u,
    0x00000007u, 0x0000001eu, 0x0000001cu, 0x00000014u, 0x0004003du, 0x00000023u, 0x00000026u, 0x00000025u,
    0x00070058u, 0x00000028u, 0x0000002au, 0x00000026u, 0x0000001eu, 0x00000002u, 0x00000029u, 0x0008004fu,
    0x0000001fu, 0x0000002bu, 0x0000002au, 0x0000002au, 0x00000000u, 0x00000001u, 0x00000002u, 0x00050094u,
    0x00000006u, 0x00000033u, 0x0000002bu, 0x00000032u, 0x0007000cu, 0x00000006u, 0x00000037u, 0x00000001u,
    0x00000028u, 0x00000033u, 0x00000036u, 0x0006000cu, 0x00000006u, 0x00000038u, 0x00000001u, 0x0000001cu,
    0x00000037u, 0x0004003du, 0x0000000au, 0x0000003du, 0x0000003cu, 0x00050041u, 0x00000044u, 0x00000045u,
    0x00000041u, 0x0000003du, 0x0003003eu, 0x00000045u, 0x00000038u, 0x000300e1u, 0x00000046u, 0x00000047u,
    0x000400e0u, 0x00000048u, 0x00000048u, 0x00000047u, 0x000200f9u, 0x0000004bu, 0x000200f8u, 0x0000004bu,
    0x000700f5u, 0x0000000au, 0x0000007fu, 0x0000004au, 0x00000005u, 0x00000064u, 0x0000004eu, 0x000500acu,
    0x00000052u, 0x00000053u, 0x0000007fu, 0x00000051u, 0x000400f6u, 0x0000004du, 0x0000004eu, 0x00000000u,
    0x000400fau, 0x00000053u, 0x0000004cu, 0x0000004du, 0x000200f8u, 0x0000004cu, 0x000500b0u, 0x00000052u,
    0x00000056u, 0x0000003du, 0x0000007fu, 0x000300f7u, 0x00000058u, 0x00000000u, 0x000400fau, 0x00000056u,
    0x00000057u, 0x00000058u, 0x000200f8u, 0x00000057u, 0x00050080u, 0x0000000au, 0x0000005cu, 0x0000003du,
    0x0000007fu, 0x00050041u, 0x00000044u, 0x0000005du, 0x00000041u, 0x0000005cu, 0x0004003du, 0x00000006u,
    0x0000005eu, 0x0000005du, 0x0004003du, 0x00000006u, 0x00000060u, 0x00000045u, 0x00050081u, 0x00000006u,
    0x00000061u, 0x00000060u, 0x0000005eu, 0x0003003eu, 0x00000045u, 0x00000061u, 0x000200f9u, 0x00000058u,
    0x000200f8u, 0x00000058u, 0x000300e1u, 0x00000046u, 0x00000047u, 0x000400e0u, 0x00000048u, 0x00000048u,
    0x00000047u, 0x000200f9u, 0x0000004eu, 0x000200f8u, 0x0000004eu, 0x000500c2u, 0x0000000au, 0x00000064u,
    0x0000007fu, 0x00000046u, 0x000200f9u, 0x0000004bu, 0x000200f8u, 0x0000004du, 0x000500aau, 0x00000052u,
    0x00000066u, 0x0000003du, 0x00000051u, 0x000300f7u, 0x00000068u, 0x00000000u, 0x000400fau, 0x00000066u,
    0x00000067u, 0x00000068u, 0x000200f8u, 0x00000067u, 0x00050041u, 0x0000003bu, 0x0000006bu, 0x0000006au,
    0x00000046u, 0x0004003du, 0x0000000au, 0x0000006cu, 0x0000006bu, 0x00050041u, 0x0000003bu, 0x0000006du,
    0x0000000du, 0x00000051u, 0x0004003du, 0x0000000au, 0x0000006eu, 0x0000006du, 0x00050084u, 0x0000000au,
    0x0000006fu, 0x0000006cu, 0x0000006eu, 0x00050041u, 0x0000003bu, 0x00000070u, 0x0000006au, 0x00000051u,
    0x0004003du, 0x0000000au, 0x00000071u, 0x00000070u, 0x00050080u, 0x0000000au, 0x00000072u, 0x0000006fu,
    0x00000071u, 0x00050041u, 0x00000044u, 0x0000007au, 0x00000041u, 0x00000078u, 0x0004003du, 0x00000006u,
    0x0000007bu, 0x0000007au, 0x00060041u, 0x0000007cu, 0x0000007du, 0x00000076u, 0x00000078u, 0x00000072u,
    0x0003003eu, 0x0000007du, 0x0000007bu, 0x000200f9u, 0x00000068u, 0x000200f8u, 0x00000068u, 0x000100fdu,
    0x00010038u,
};
inline constexpr std::size_t kReductionVulkanComputeSpirVByteSize = sizeof(kReductionVulkanComputeSpirV);

inline constexpr std::string_view kReductionVulkanComputeWgsl =
    R"CNA_SHADER(// reduction.vulkan.comp.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct Partials {
    partials: array<f32>,
}

var<private> gl_NumWorkGroups_1: vec3<u32>;
var<private> gl_GlobalInvocationID_1: vec3<u32>;
@group(0) @binding(0)
var uScene_cnaTexture: texture_2d<f32>;
@group(0) @binding(32)
var uScene_cnaSampler: sampler;
var<private> gl_LocalInvocationIndex_1: u32;
var<workgroup> sharedSums: array<f32, 64>;
var<private> gl_WorkGroupID_1: vec3<u32>;
@group(0) @binding(1)
var<storage, read_write> unnamed: Partials;

fn main_1() {
    var grid: vec2<f32>;
    var uv: vec2<f32>;
    var colour: vec3<f32>;
    var luminance: f32;
    var value: f32;
    var local: u32;
    var stride: u32;
    var group: u32;

    let _e33 = gl_NumWorkGroups_1;
    grid = vec2<f32>((_e33.xy * vec2<u32>(8u, 8u)));
    let _e37 = gl_GlobalInvocationID_1;
    let _e42 = grid;
    uv = ((vec2<f32>(_e37.xy) + vec2(0.5f)) / _e42);
    let _e44 = uv;
    let _e45 = textureSampleLevel(uScene_cnaTexture, uScene_cnaSampler, _e44, 0f);
    colour = _e45.xyz;
    let _e47 = colour;
    luminance = dot(_e47, vec3<f32>(0.2126f, 0.7152f, 0.0722f));
    let _e49 = luminance;
    value = log(max(_e49, 0.0001f));
    let _e52 = gl_LocalInvocationIndex_1;
    local = _e52;
    let _e53 = local;
    let _e54 = value;
    sharedSums[_e53] = _e54;
    workgroupBarrier();
    workgroupBarrier();
    stride = 32u;
    loop {
        let _e56 = stride;
        if (_e56 > 0u) {
            let _e58 = local;
            let _e59 = stride;
            if (_e58 < _e59) {
                let _e61 = local;
                let _e62 = local;
                let _e63 = stride;
                let _e66 = sharedSums[(_e62 + _e63)];
                let _e68 = sharedSums[_e61];
                sharedSums[_e61] = (_e68 + _e66);
            }
            workgroupBarrier();
            workgroupBarrier();
            continue;
        } else {
            break;
        }
        continuing {
            let _e71 = stride;
            stride = (_e71 >> bitcast<u32>(1u));
        }
    }
    let _e74 = local;
    if (_e74 == 0u) {
        let _e77 = gl_WorkGroupID_1[1u];
        let _e79 = gl_NumWorkGroups_1[0u];
        let _e82 = gl_WorkGroupID_1[0u];
        group = ((_e77 * _e79) + _e82);
        let _e84 = group;
        let _e86 = sharedSums[0i];
        unnamed.partials[_e84] = _e86;
    }
    return;
}

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(num_workgroups) gl_NumWorkGroups: vec3<u32>, @builtin(global_invocation_id) gl_GlobalInvocationID: vec3<u32>, @builtin(local_invocation_index) gl_LocalInvocationIndex: u32, @builtin(workgroup_id) gl_WorkGroupID: vec3<u32>) {
    gl_NumWorkGroups_1 = gl_NumWorkGroups;
    gl_GlobalInvocationID_1 = gl_GlobalInvocationID;
    gl_LocalInvocationIndex_1 = gl_LocalInvocationIndex;
    gl_WorkGroupID_1 = gl_WorkGroupID;
    main_1();
}
)CNA_SHADER";

inline constexpr std::array<PayloadProvenance, 4> kPayloads = {{
    {"kReductionEsComputeSource", "reduction.es.comp.glsl", "59c462baec909f0ee870b97d0d4c0826e8e8b66eeef07e5d0a21b7fd23cd119d", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kReductionDesktopComputeSource", "reduction.desktop.comp.glsl", "96e48c3df68ea695470d40bc1cd96a5261bda1121288fb3c4447f805a5b22be0", "glsl", "glsl", "compute", "text", "main"},
    {"kReductionVulkanComputeSpirV", "reduction.vulkan.comp.glsl", "fae1808a0f4ce0a2634dee5b2070566896a9eccaaac040d25b568928de6ada42", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
    {"kReductionVulkanComputeWgsl", "reduction.vulkan.comp.glsl", "fae1808a0f4ce0a2634dee5b2070566896a9eccaaac040d25b568928de6ada42", "wgsl", "vulkan-glsl", "compute", "wgsl", "main"},
}};

} // namespace CnaRoom::Effects::detail::AutoExposureGenerated
